spring.application.name=patient-service
#Using In memory database
# Database Connection Settings
#spring.datasource.url=jdbc:h2:mem:testes
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=user
#spring.datasource.password=pass
#
## JPA / Hibernate Settings
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
## H2 Console Settings
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
#spring.h2.console.enable=true
## Since you are using port 4000

server.port=4000
logging.level.root=info;
spring.datasource.url=jdbc:mysql://localhost:3306/db
spring.datasource.username=admin_user
spring.datasource.password=admin_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true